name: Certified Images

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  dockerhub:
    name: DockerHub
    strategy:
      matrix:
        java: [8, 11, 17, latest]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set up emulator for non-native platforms (the GH runners are on amd64 architecture)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      # Docker Buildx allows easy cross-building for different platforms
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # build-push-action relies on Docker Buildx
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: gatlingcorp/classic-openjdk:${{ matrix.java }}
          build-args: |
            BASE_IMAGE=gatlingcorp/openjdk-base:${{ matrix.java }}-jre-headless
